---
# https://rpmsphere.github.io/

- debug:
    msg: 'Insecure! disable_gpg_check Exposure to "Supply chain Attack". Todo: fix this'
  when: disable_gpg_check

- name: Install rpmsphere-release
  become: true
  ansible.builtin.dnf:
    name: "{{ rpmsphere_package_url }}"
    state: latest
    disable_gpg_check: true
